# Generated by Django 5.1.1 on 2024-10-03 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
