# Generated by Django 5.1.1 on 2024-10-03 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_alter_article_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('politica', 'Política'), ('deportes', 'Deportes'), ('tecnologia', 'Tecnología'), ('salud', 'Salud')], max_length=100),
        ),
    ]
